name: Tags
main: no.jckf.tags.Tags
version: 1.1
commands:
   op:
      description: Gives the specified player operator status
      usage: /<command> <player>
   deop:
      description: Takes the specified player's operator status
      usage: /<command> <player>
